#!/bin/bash

which vlc > /dev/null

if [[ $! -eq 1 || $! -eq 127 ]]; then 
	echo "manteghi nabood" 
else 
	echo "manteghie!"
fi

MYFILE=/dev/null 

if [[ -f $MYFILE ]]; then
	echo "suuui"
elif [[ -b $MYFILE ]]; then

	echo "naaah fam"
elif [[ -c $MYFILE ]]; then
	echo "wait whaat"
else 
	echo "Am I a joke to u ??"
fi		

unset NEWFILE

NEWFILE=""
 
if [ -z $NEWFILE ]; then
	echo "emptyyyy"
elif [ -n $NEWFILE ]; then 
	echo "noooope smthing there"
else 
	echo " HOW THOUGH"
fi


#read -p "Select ur item : " CATEGORY
Myfunction() { 
	PRICE="The price is"
	select CATEGORY in Fruit Food Furniture exit; do 
		case $CATEGORY in 
			Fruit)
				echo "Select your item : " 
				select ITEMS in Banana Apple Pineapple back exit; do
					case $ITEMS in 
						Banana)
							echo $PRICE" 3$"
							;;
						Apple)
							echo $PRICE"3.5$"
							;;
						Pineapple)
							echo $PRICE" 5$"
							;;
						back) 
							Myfunction	
							;;	
						exit)
							exit 0
							;;
						*)
							echo "not found"
							;;
					esac		
				done		
				;;
			Food) 
				echo "Select your item : " 
				select ITEMS in Burger Pizza Pasta back exit; do
					case $ITEMS in 
						Burger)
							echo $PRICE" 13$"
							;;
						Pizza)
							echo $PRICE" 18.5$"
							;;
						Pasta)
							echo $PRICE" 10$"
							;;
						back) 
							Myfunction	
							;;	
						exit)
							exit 0
							;;
						*)
							echo "not found"
							;;
					esac		
				done		
				;;
				
			Furniture)
				echo "Select your item : " 
				select ITEMS in Sofa "Persian Carpet" "Dining Table" back exit; do
					case $ITEMS in 
						Sofa)
							echo $PRICE" 250$"
							;;
						"Dining Table")
							echo $PRICE" 150$"
							;;
						"Persian Carpet")
							echo $PRICE" 300$"
							;;
						back) 
							Myfunction	
							;;	
						exit)
							exit 0
							;;
						*)
							echo "not found"
							;;
					esac		
				done		
				
				;;
				
			exit)
				exit 0
				;;
				
			*)
				echo "not found"
				;;
				
		esac					
	done
}

Myfunction
